### ISSUE TITLE
User tracking?

### ISSUE THREAD

**Issue by alexdrans** [yayuhh/icecreambar#8]
How are users tracked using this module?

**Comment by jmonster** [comment]
they aren't since we only use this to track errors; if that's a feature you'd find useful I'd be happy to help work with you on a PR -- just make sure it's an optional feature.

**Comment by alexdrans** [comment]
There you go @jmonster, let me know if you want me to change anything. Thanks for the quick reply!

**Comment by jmonster** [comment]
merged + published (last week)
